services:
  nixos-homepage:
    build:
      context: .
    environment:
      HOST: "0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command:
      - nix
      - develop
      - --command
      - serve