blank_issues_enabled: true
contact_links:
  - name: NixOS Community Marketing Team
    url: https://discourse.nixos.org/c/governance/marketing
    about: Please ask and answer questions about our marketing efforts here.
