[[commercial-provider]]
name = "Black River Software"
url = "http://blackriversoft.com/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Enlambda"
url = "https://www.enlambda.com/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "five binaries"
url = "https://www.fivebinaries.com/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Helsinki Systems"
url = "https://helsinki-systems.de"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Mayflower"
url = "https://nixos.mayflower.consulting"
logo = ""
description = """
"""

[[commercial-provider]]
name = "nixcloud"
url = "https://nixcloud.io/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "NumTide Ltd"
url = "https://www.numtide.com/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Obsidian Systems"
url = "https://obsidian.systems"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Serokell"
url = "https://serokell.io/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Tweag"
url = "https://tweag.io/"
logo = ""
description = """
"""

[[commercial-provider]]
name = "Immutable Solutions"
url = "https://immutablesolutions.com/"
logo = ""
description = """
"""
